//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroChamados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tabela
    {
        public long codigo { get; set; }
        public string Solicitante { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
    }
}
